// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * SaveFile
       * @param {Array<Line>} arg1 - Go Type: []main.Line
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<number>}  - Go Type: int
       */
      "SaveFile": (arg1, arg2) => {
        return window.go.main.App.SaveFile(arg1, arg2);
      },
    },
  },

};
export default go;
