// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * OpenFile
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenFile": () => {
        return window.go.main.App.OpenFile();
      },
      /**
       * SaveFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<number>}  - Go Type: int
       */
      "SaveFile": (arg1) => {
        return window.go.main.App.SaveFile(arg1);
      },
    },
  },

};
export default go;
